apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: nginx-deploy
spec:
 replicas: 1
 template:
  metadata: 
   labels:
    app: nginx-deploy
  spec:
   containers:
   - name: nginx
     image: nginx:1.8
     ports:
     - containerPort: 80
